export const SEARCH_JOBS = 'SEARCH_JOBS'
export const GET_JOBS = 'GET_JOBS'
export const GET_JOB = 'GET_JOB'
export const CLEAR_JOBS = 'CLEAR_JOBS'
export const SET_LOADING = 'SET_LOADING'
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'